### ISSUE TITLE
Code highlighting in the wiki

### ISSUE THREAD

**Issue by Eireen** [jonny64/mr-git-cli#110]
Please consider adding highlighting via ```sh prefix to the code snippets in the wiki to make it more reader-friendly. I would do it myself, but unfortunately GitHub does not support PRs to the wiki. Perhaps another option is to convert the wiki to a README file. Thanks.

**Comment by jonny64** [comment]
aha, https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

unclosed quotes now can be seen and FIXed https://github.com/jonny64/mr-git-cli/wiki/Home/_compare/51c8aa01e37f087fc34ec94702a09485e8df2fad...ba210f398bcea6724b59a41be7571ce2ea51221b

thanks!
